### ISSUE TITLE
how to set up the 'ims' 

### ISSUE THREAD

**Issue by XiaoKangW** [google/nerfactor#12]
hi,xiuming.

 I want to learn how to set up the value of  'ims' when converting the brdf dataset.
and is there a relationship between  'ims' and 'imh'?

thanks in advance!

**Comment by JiuTongBro** [comment]
It seems the ims shall be set to 512 to run the default scripts.

[https://github.com/google/nerfactor/issues/1](url)

**Comment by xiumingzhang** [comment]
My apologies for the super delayed response!

`ims` means image size, where image height and width are the same. `imh` means image height.
