### ISSUE TITLE
Trained Weights

### ISSUE THREAD

**Issue by SteEsp** [google/nerfactor#14]
Hi, I find NeRFactor results very impressive; it really is an outstanding and inspiring work.
Would it be possibile for you to share the trained weights you have used to obtain such results? 
I would like to include NeRFactor scene representations into my path-tracer and having them available to compare the results would surely speed-up my work.

Thank you!

**Comment by xiumingzhang** [comment]
My apologies for the super delayed response!

In case you still need them. they can be found [here](https://xiuming.info/projects/nerfactor/).
