### ISSUE TITLE
NerFactor generated images from the quantitative evaluations

### ISSUE THREAD

**Issue by jmunkberg** [google/nerfactor#16]
Congrats to a nice paper!

Would it be possible to access the NerFactor output images for the view synthesis comparison (column III, row "NerfFactor") in Table 1 (the eight validation images for each of the four scenes), in order to generate other metrics, check the metric and visual quality per image and per scene.

**Comment by xiumingzhang** [comment]
My apologies for the super delayed response!

In case you still need them. they can be found in 
```
${scene}_nerfactor/lr5e-3/vis_vali/epoch000000100
```
if you download and unzip the pre-trained model folders released [here](https://xiuming.info/projects/nerfactor/).

**Comment by jmunkberg** [comment]
Thanks. We generated the required images using your public code. Results are reported here: https://nvlabs.github.io/nvdiffrec/

**Comment by xiumingzhang** [comment]
Oops, I wish I were more helpful. Great work, @jmunkberg!
