### ISSUE TITLE
Question about Camera Models for synthetic/real datasets

### ISSUE THREAD

**Issue by JulianKnodt** [google/nerfactor#17]
Hey, thank you for the awesome work.

I was attempting to replicate your work and realized that I had made the assumption that the camera model for the synthetic and real datasets was identical. I assume this is not true, but I had some trouble finding the camera model for the real data. Where in the code is it, or what's the difference between the synthetic and real camera models?

**Comment by xiumingzhang** [comment]
Hi, my apologies for the super delayed response.

Both the synthetic and real camera models are assumed to be simple perspective cameras.
