### ISSUE TITLE
How to calculate geometry buffers from MVS geometry ?

### ISSUE THREAD

**Issue by sanskar107** [google/nerfactor#21]
I am trying to replace NeRF with my own geometry. The script `trainvali_mvs_run.sh` for joint optimisation uses `shape_mvs` dataset, which in turn needs the same `alpha`, `normals`, and `lvis`.
I couldn't find any script to generate these geometry buffers from MVS geometry instead of NeRF. Could you please help ?

**Comment by xiumingzhang** [comment]
Hi, thanks for the request. I've just added the scripts we used to convert MVS shape output into our surface points, normals, and light visibility: https://github.com/google/nerfactor/tree/main/data_gen/dtu_mvs. Please feel free to reopen this issue if you have more questions.
