### ISSUE TITLE
questions about hdrs.

### ISSUE THREAD

**Issue by sunwenzhang1996** [google/nerfactor#23]
Hi, i downloaded some hdr from poly heaven. But i find some differences between the hdr downloaded and the hdr provided. The max value of the sunset i download is about 300000, but the provide hdr is about 80. Is there any pre-process while dealing with the new hdr map?

**Comment by xiumingzhang** [comment]
Hi, the max value of your HDR map sounds reasonable. I didn't do preprocessing on the HDR maps; it might be just that the HDR maps I downloaded have a lower dynamic range than yours. The approach should still work with your HDR maps, but you may need to pay attention to the scale and avoid clipping when you produce the final rendering in JPEG, for example.
