### ISSUE TITLE
OOM at II. Joint Optimization in Training, Validation, and Testing

### ISSUE THREAD

**Issue by Woolseyyy** [google/nerfactor#29]
It keeps out of memory at  II. Joint Optimization in Training, Validation, and Testing. Note that it is NOT out of GPU memory but cpu memory.  And it seems to happen at `for batch_i, batch in enumerate(datapipe_train):`
I run on a machine with 1 3090 GPU, 20 cpu cores, 80 GB memory. Any suggestion would help!

**Comment by xiumingzhang** [comment]
Try reducing MLP chunk size? Feel free to reopen this if you still have problems.
