### ISSUE TITLE
Can we extract mesh from the system by marching cubes?

### ISSUE THREAD

**Issue by jzhangbs** [google/nerfactor#35]
Thanks for the released code! I would like to ask whether we can extract mesh by marching cubes. Is this function implemented? If not, how can we access the density field of NeRF in the model? After a quick look into the code, it seems that the system directly read xyz, normal etc. from input, and it is not straightforward to get the density values.

**Comment by xiumingzhang** [comment]
This work models geometry with surfaces (just vertices, without connectivity), so it starts off with the surface from NeRF and then refines the surface vertices' locations. As such, there is no concept of volume density in NeRFactor; the only volume density in the pipeline is that of NeRF, from which we extracted the initial surface.
