### ISSUE TITLE
About the intrinsic matrix in data

### ISSUE THREAD

**Issue by zzhat0706** [google/nerfactor#6]
Thanks for the great work and data! 

I am transfering the camera pose data to other format. But neighter metadata.json nor *_camera.json had no intrinsic data inside(focal length and cx, cy). 

Also I used .blender's focal data, but either way not worked for me, maybe this is because .blender file use different extrinsic matrix. 

So can you tell me your intrinsic values or the way to know those values? thx

**Comment by xiumingzhang** [comment]
Hi. Sorry for the late reply but are you referring to the data released by
us?

If so, `metadata.json` has a field called `cam_angle_x`, which you can
convert to the focal length using simple trigonometric identities.

As for `cx` or `cy`, you can assume them to be always half of the image
width or height.

Closing this but feel free to reopen this issue with more questions.
